### ISSUE TITLE
code 5:  Why is steps "printCounter % 40 == 0" instead of "printCounter % maxChanges"?

### ISSUE THREAD

**Issue by bynarron** [akondrahman/59115ASE#9]
I'm reading through the code and the hard-coded "printCounter % 40" is a bit confusing.  Should it not be set to maxChanges?  Or is this number just arbitrary so that it fits in the terminal?

**Comment by akondrahman** [comment]
_printCounter_ keeps track of the number of lines to show. We did the same thing in hw/code/4, so that we display 40th lines. hw/code/4 required to display  '+/?/!' in one line, and print each line every 40 times. hw/code/5 requires a similar output as well. 

Btw, I have also changed how mutate for p >= random.random(), as per Dr. Menzies' suggestion from Thursday.

**Comment by timm** [comment]
help... is this printCounter thing a question to me? if so, some context please.

**Comment by bynarron** [comment]
Sorry, Dr. Menzies.  No, to Akond.

**Comment by timm** [comment]
no worries. good to see you working with such enthusiasm!
